# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogConfiguration', '0003_auto_20170212_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprodlogsloca',
            name='srv1_name_dir',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customerprodlogsloca',
            name='srv2_name_dir',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customerprodlogsloca',
            name='srv98_name_dir',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customerprodlogsloca',
            name='srv99_name_dir',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='customerprodlogsloca',
            name='add_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='customerprodlogsloca',
            name='appsrv_localws_logpath',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customerprodlogsloca',
            name='appsrv_tools_logpath',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customerprodlogsloca',
            name='cust_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='CM_JIRA_issue',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='cust_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='error_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='error_repeat_app1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='error_repeat_app2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='error_repeat_app98',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='error_repeat_app99',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='existing_CM_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='error_reporting_jira',
            name='reoprt_date',
            field=models.DateField(default='2011-11-21'),
        ),
    ]
