# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsAnalyzed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=90)),
                ('logs_fileName', models.CharField(max_length=90)),
                ('logs_analyzed_Datetime', models.DateField()),
                ('Logs_FinalFile', models.BinaryField()),
            ],
        ),
    ]
