# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centurionapi', '0002_customerprodlogsloca_error_reporting_jira_temptab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProdLogsLoca',
        ),
        migrations.DeleteModel(
            name='Error_Reporting_JIRA',
        ),
        migrations.DeleteModel(
            name='temptab',
        ),
    ]
